// src/ui-solid/components/StatusBar.jsx
import { Show } from 'solid-js';
import { Box, Typography } from '@suid/material';

export default function StatusBar(props) {
    return (
        <Box
            sx={{
                p: 0.5,
                px: 2,
                borderTop: 1,
                borderColor: 'divider',
                bgcolor: 'background.paper',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                zIndex: (theme) => theme.zIndex.drawer + 1,
                minHeight: 24,
                width: '100%',
                flexShrink: 0,
            }}
        >
            <Typography variant="caption" color="text.secondary">
                <Show when={props.statusText} fallback="Ready">
                    {props.statusText}
                </Show>
            </Typography>
            <Show when={props.providerCredits}>
                <Typography variant="caption" color="text.secondary">
                    {props.providerCredits}
                </Typography>
            </Show>
        </Box>
    );
}

// src/ui/components/StatusBar.jsx
import React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

export default function StatusBar({ statusText, providerCredits }) {
  return (
    <Box
      sx={{
        position: 'fixed',
        bottom: 0, // At the very bottom
        left: 0,
        right: 0,
        height: '1.75rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        px: '0.75rem',
        borderTop: 1,
        borderColor: 'divider',
        bgcolor: 'background.paper',
        fontSize: '0.75rem',
        zIndex: (theme) => theme.zIndex.appBar - 1,
      }}
    >
      <Typography
        variant="caption"
        sx={{ fontSize: '0.7rem', color: 'text.secondary', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}
      >
        {statusText || ''}
      </Typography>
      <Typography
        variant="caption"
        sx={{ fontSize: '0.7rem', color: 'text.secondary', whiteSpace: 'nowrap' }}
      >
        {providerCredits}
      </Typography>
    </Box>
  );
}
