// src/ui-solid/components/TreePane.jsx
import { createSignal, createEffect, For, Show, createMemo } from 'solid-js';
import {
    Box, Typography, List, ListItemButton, ListItemText, ListItemIcon, IconButton, Button
} from '@suid/material';
import ExpandLessIcon from '@suid/icons-material/ExpandLess';
import ExpandMoreIcon from '@suid/icons-material/ExpandMore';
import PersonIcon from '@suid/icons-material/Person';
import SettingsIcon from '@suid/icons-material/Settings';
import RecordVoiceOverIcon from '@suid/icons-material/RecordVoiceOver';
import MusicNoteIcon from '@suid/icons-material/MusicNote';
import GraphicEqIcon from '@suid/icons-material/GraphicEq';
import TerminalIcon from '@suid/icons-material/Terminal';
import HistoryIcon from '@suid/icons-material/History';
import StarIcon from '@suid/icons-material/Star';
import StarBorderIcon from '@suid/icons-material/StarBorder';
import FolderIcon from '@suid/icons-material/Folder';
import AssessmentIcon from '@suid/icons-material/Assessment';
import AddIcon from '@suid/icons-material/Add';

import { DESIGN_SYSTEM } from '../theme/designSystem.js';
import { TREE_INDENT } from '../constants.js';
import ViewTree from './ViewTree.jsx';
import { PRESET_VIEWS, buildViewTree, getAllViews, getStickyName } from '../utils/viewEngine.js';
import Collapse from './Collapse.jsx';

function nodeKey(type, id) {
    return `${type}:${id}`;
}

export default function TreePane(props) {
    const selectedId = () => props.selectedNode ? nodeKey(props.selectedNode.type, props.selectedNode.id) : null;

    // --- Persistence ---
    const [expanded, setExpanded] = createSignal((() => {
        try {
            const saved = localStorage.getItem('moo-tree-expanded');
            return saved ? JSON.parse(saved) : { views: true, favorites: true };
        } catch (e) {
            return { views: true, favorites: true };
        }
    })());

    const [pinnedIds, setPinnedIds] = createSignal((() => {
        try {
            const saved = localStorage.getItem('moo-pinned-views');
            return saved ? JSON.parse(saved) : ["by-actor"];
        } catch (e) {
            return ["by-actor"];
        }
    })());

    const saveExpanded = (newState) => {
        localStorage.setItem('moo-tree-expanded', JSON.stringify(newState));
    };

    const handleToggle = (key) => {
        setExpanded(prev => {
            const newState = { ...prev, [key]: !prev[key] };
            saveExpanded(newState);
            return newState;
        });
    };

    const togglePin = (e, id) => {
        e.stopPropagation();
        setPinnedIds(prev => {
            const newState = prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id];
            localStorage.setItem('moo-pinned-views', JSON.stringify(newState));
            return newState;
        });
    };

    const createNewView = (e, category) => {
        e.stopPropagation();
        const id = `custom-${category}-${Date.now()}`;
        const newView = {
            id,
            name: '', // Sticky title will handle display
            category,
            levels: [
                { field: 'actor_id', displayField: 'actor_name', icon: 'person' },
                { field: 'content_id', displayField: 'cue_id', icon: 'content', isTerminal: true }
            ]
        };
        props.onCustomViewsChange([...props.customViews, newView]);
        // Auto-select the new view for editing
        props.onSelect({ type: 'view-config', id: newView.id });
    };

    // --- Views logic ---
    const allViews = createMemo(() => getAllViews(props.customViews));
    const pinnedViews = createMemo(() => allViews().filter(v => pinnedIds().includes(v.id)));
    const workflowViews = createMemo(() => allViews().filter(v => v.category === 'view' && !pinnedIds().includes(v.id)));
    const summaryViews = createMemo(() => allViews().filter(v => v.category === 'summary' && !pinnedIds().includes(v.id)));

    const categories = createMemo(() => [
        { id: 'favorites', name: 'favorites', icon: <StarIcon sx={{ fontSize: '0.875rem' }} />, items: pinnedViews() },
        { id: 'views', name: 'views', icon: <FolderIcon sx={{ fontSize: '0.875rem' }} />, items: workflowViews(), canAdd: true },
        { id: 'summaries', name: 'summaries', icon: <AssessmentIcon sx={{ fontSize: '0.875rem' }} />, items: summaryViews(), canAdd: true },
        {
            id: 'system', name: 'system', icon: <SettingsIcon sx={{ fontSize: '0.875rem' }} />, items: [
                { id: 'console', name: 'console', nodeType: 'console', nodeId: 'console', icon: <TerminalIcon sx={{ fontSize: '0.75rem' }} /> },
                { id: 'history', name: 'history', nodeType: 'history', nodeId: 'logs', icon: <HistoryIcon sx={{ fontSize: '0.75rem' }} /> },
                {
                    id: 'defaults', name: 'defaults', nodeType: 'defaults', nodeId: 'providers', icon: <SettingsIcon sx={{ fontSize: '0.75rem' }} />,
                    isDefaults: true,
                    children: ['dialogue', 'music', 'sfx'].map(type => ({
                        id: type, name: `${type} (elevenlabs)`, nodeType: 'provider-default', nodeId: type,
                        icon: type === 'dialogue' ? <RecordVoiceOverIcon sx={{ fontSize: '0.75rem' }} /> :
                            type === 'music' ? <MusicNoteIcon sx={{ fontSize: '0.75rem' }} /> : <GraphicEqIcon sx={{ fontSize: '0.75rem' }} />
                    }))
                }
            ]
        }
    ]);

    const handleSelect = (type, id) => {
        props.onSelect({ type, id });
    };

    const handleViewSelect = (e, item) => {
        // If they click the text/expand area, toggle expand.
        // If they click specifically to edit (handled later by selection logic), standard behavior.
        // For now, let's say selecting a view-config is a separate action or happens when selecting the group.

        // Actually, let's make it so clicking a View Group selects it for config IN ADDITION to toggling it.
        handleToggle(`item-${item.id}`);
        props.onSelect({ type: 'view-config', id: item.id });
    };

    return (
        <Box
            sx={{
                width: props.width || 300,
                flexShrink: 0,
                borderRight: 1,
                borderColor: 'divider',
                height: '100%',
                maxHeight: '100%',
                display: 'flex',
                flexDirection: 'column',
                overflow: 'hidden',
                backgroundColor: 'background.paper'
            }}
        >
            <List dense disablePadding sx={{ px: '0.3125rem', pt: '0.5rem', pb: '0.625rem', flexGrow: 1, overflowY: 'auto', overflowX: 'hidden', minHeight: 0 }}>
                <For each={categories()}>
                    {(cat) => (
                        <Box sx={{ mb: '0.5rem' }}>
                            <ListItemButton
                                sx={{
                                    pl: `${TREE_INDENT.BASE}px`,
                                    pr: '0.25rem',
                                    color: 'text.secondary',
                                    fontWeight: 700,
                                    minHeight: '1.5rem',
                                    '&:hover': { bgcolor: 'transparent' }
                                }}
                                onClick={() => handleToggle(cat.id)}
                            >
                                <ListItemIcon sx={{ minWidth: 'auto', mr: '0.375rem', color: 'primary.main', opacity: 0.8 }}>
                                    {cat.icon}
                                </ListItemIcon>
                                <ListItemText
                                    primary={cat.name}
                                    primaryTypographyProps={{
                                        fontSize: '0.75rem',
                                        fontWeight: 800,
                                        textTransform: 'uppercase',
                                        letterSpacing: '0.08em'
                                    }}
                                />
                                <Box sx={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                                    <Show when={cat.canAdd}>
                                        <IconButton size="small" onClick={(e) => createNewView(e, cat.id === 'views' ? 'view' : 'summary')} sx={{ p: '2px', opacity: 0.6, '&:hover': { opacity: 1, color: 'primary.main' } }}>
                                            <AddIcon sx={{ fontSize: '0.9rem' }} />
                                        </IconButton>
                                    </Show>
                                    <Box sx={{ display: 'flex', alignItems: 'center', p: 0, m: 0, opacity: 0.5 }}>
                                        {expanded()[cat.id] ? <ExpandLessIcon sx={{ fontSize: '0.75rem' }} /> : <ExpandMoreIcon sx={{ fontSize: '0.75rem' }} />}
                                    </Box>
                                </Box>
                            </ListItemButton>

                            <Collapse in={expanded()[cat.id]}>
                                <List disablePadding>
                                    <For each={cat.items}>
                                        {(item) => {
                                            const itemKey = `item-${item.id}`;
                                            const isView = item.category === 'view' || item.category === 'summary';
                                            const isSelected = () => props.selectedNode?.type === 'view-config' && props.selectedNode?.id === item.id;

                                            return (
                                                <Box>
                                                    <ListItemButton
                                                        sx={{
                                                            pl: `${TREE_INDENT.BASE + TREE_INDENT.STEP}px`,
                                                            pr: '0.25rem',
                                                            py: '0.125rem',
                                                            ...DESIGN_SYSTEM.treeItem
                                                        }}
                                                        selected={isSelected() || (!isView && selectedId() === nodeKey(item.nodeType, item.nodeId))}
                                                        onClick={(e) => isView ? handleViewSelect(e, item) : handleSelect(item.nodeType, item.nodeId)}
                                                    >
                                                        <ListItemIcon sx={{ minWidth: 'auto', mr: '0.375rem' }}>
                                                            {isView ? (
                                                                item.category === 'summary' ? <AssessmentIcon sx={{ fontSize: '0.75rem', opacity: 0.7 }} /> : <FolderIcon sx={{ fontSize: '0.75rem', opacity: 0.7 }} />
                                                            ) : item.icon}
                                                        </ListItemIcon>
                                                        <ListItemText
                                                            primary={getStickyName(item)}
                                                            primaryTypographyProps={{
                                                                fontSize: '0.9rem',
                                                                lineHeight: '1.125rem',
                                                                fontWeight: isView ? 600 : 400
                                                            }}
                                                        />

                                                        <Box sx={{ display: 'flex', alignItems: 'center', gap: '2px', ml: 'auto' }}>
                                                            {isView && (
                                                                <IconButton size="small" onClick={(e) => togglePin(e, item.id)} sx={{ p: 0, color: pinnedIds().includes(item.id) ? 'primary.main' : 'text.disabled', opacity: 0.7 }}>
                                                                    {pinnedIds().includes(item.id) ? <StarIcon sx={{ fontSize: '0.75rem' }} /> : <StarBorderIcon sx={{ fontSize: '0.75rem' }} />}
                                                                </IconButton>
                                                            )}
                                                            {isView && (
                                                                <IconButton
                                                                    size="small"
                                                                    onClick={(e) => { e.stopPropagation(); props.onSelect({ type: 'root', id: 'root' }); }}
                                                                    sx={{ p: 0, opacity: 0.6, '&:hover': { opacity: 1, color: 'primary.main' } }}
                                                                >
                                                                    <AddIcon sx={{ fontSize: '0.9rem' }} />
                                                                </IconButton>
                                                            )}
                                                            {(isView || item.isDefaults) && (
                                                                <Box onClick={(e) => { e.stopPropagation(); handleToggle(itemKey); }} sx={{ display: 'flex', alignItems: 'center', opacity: 0.5 }}>
                                                                    {expanded()[itemKey] ? <ExpandLessIcon sx={{ fontSize: '0.75rem' }} /> : <ExpandMoreIcon sx={{ fontSize: '0.75rem' }} />}
                                                                </Box>
                                                            )}
                                                        </Box>
                                                    </ListItemButton>

                                                    <Collapse in={expanded()[itemKey]}>
                                                        <Show when={isView}>
                                                            <ViewTree
                                                                viewId={item.id}
                                                                viewName={getStickyName(item)}
                                                                tree={buildViewTree(item.id, {
                                                                    actors: props.actors,
                                                                    sections: props.sections,
                                                                    content: props.content,
                                                                    takes: props.takes,
                                                                    scenes: props.scenes || []
                                                                }, props.customViews)}
                                                                selectedNode={props.selectedNode}
                                                                onSelect={props.onSelect}
                                                                baseDepth={2}
                                                                onAddActor={() => props.onSelect({ type: 'root', id: 'root' })}
                                                                onAddScene={() => props.onSelect({ type: 'root', id: 'root' })}
                                                            />
                                                        </Show>
                                                        <Show when={item.isDefaults}>
                                                            <For each={item.children}>
                                                                {(child) => (
                                                                    <ListItemButton
                                                                        sx={{
                                                                            pl: `${TREE_INDENT.BASE + TREE_INDENT.STEP * 2}px`,
                                                                            ...DESIGN_SYSTEM.treeItem
                                                                        }}
                                                                        selected={selectedId() === nodeKey(child.nodeType, child.nodeId)}
                                                                        onClick={() => handleSelect(child.nodeType, child.nodeId)}
                                                                    >
                                                                        <ListItemIcon sx={{ minWidth: 'auto', mr: '0.375rem' }}>
                                                                            {child.icon}
                                                                        </ListItemIcon>
                                                                        <ListItemText primary={child.name} primaryTypographyProps={{ fontSize: '0.85rem' }} />
                                                                    </ListItemButton>
                                                                )}
                                                            </For>
                                                        </Show>
                                                    </Collapse>
                                                </Box>
                                            );
                                        }}
                                    </For>
                                </List>
                            </Collapse>
                        </Box>
                    )}
                </For>
            </List>

            <Box sx={{ px: '1rem', py: '0.5rem', color: 'text.secondary', borderTop: 1, borderColor: 'divider', flexShrink: 0, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.25rem 0.5rem', bgcolor: 'action.hover' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                    <Box sx={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', bgcolor: 'success.main', boxShadow: '0 0 4px rgba(0,0,0,0.2)' }} />
                    <Typography variant="caption" sx={{ fontSize: '0.6rem', fontWeight: 600 }}>Complete</Typography>
                </Box>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                    <Box sx={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', bgcolor: 'warning.main', boxShadow: '0 0 4px rgba(0,0,0,0.2)' }} />
                    <Typography variant="caption" sx={{ fontSize: '0.6rem', fontWeight: 600 }}>In Progress</Typography>
                </Box>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                    <Box sx={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', bgcolor: 'error.main', boxShadow: '0 0 4px rgba(0,0,0,0.2)' }} />
                    <Typography variant="caption" sx={{ fontSize: '0.6rem', fontWeight: 600 }}>Fault</Typography>
                </Box>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                    <Box sx={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', bgcolor: 'text.disabled', boxShadow: '0 0 4px rgba(0,0,0,0.2)' }} />
                    <Typography variant="caption" sx={{ fontSize: '0.6rem', fontWeight: 600 }}>Empty</Typography>
                </Box>
            </Box>
        </Box>
    );
}

// src/ui/components/TreePane.jsx
import React, { useState, useCallback } from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import List from '@mui/material/List';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemText from '@mui/material/ListItemText';
import ListItemIcon from '@mui/material/ListItemIcon';
import Collapse from '@mui/material/Collapse';
import ExpandLess from '@mui/icons-material/ExpandLess';
import ExpandMore from '@mui/icons-material/ExpandMore';
import PersonIcon from '@mui/icons-material/Person';
import SettingsIcon from '@mui/icons-material/Settings';
import RecordVoiceOverIcon from '@mui/icons-material/RecordVoiceOver';
import MusicNoteIcon from '@mui/icons-material/MusicNote';
import GraphicEqIcon from '@mui/icons-material/GraphicEq';
import DescriptionIcon from '@mui/icons-material/Description';
import TerminalIcon from '@mui/icons-material/Terminal';
import { DESIGN_SYSTEM } from '../theme/designSystem.js';

function nodeKey(type, id) {
  return `${type}:${id}`;
}

// Status priority: red (3) > yellow (2) > gray (1) > green (0)
const STATUS_PRIORITY = { green: 0, gray: 1, yellow: 2, red: 3 };

// Get CSS class name for status color
function getStatusClass(color) {
  const classMap = {
    'success.main': 'status-green',
    'error.main': 'status-red',
    'warning.main': 'status-yellow',
    'text.disabled': 'status-gray',
    'text.secondary': 'status-white',
  };
  return classMap[color] || 'status-default';
}

function getContentStatus(content, takes = []) {
  const contentTakes = takes.filter(t => t.content_id === content.id);
  const approvedCount = contentTakes.filter(t => t.status === 'approved').length;
  const hasRejected = contentTakes.some(t => t.status === 'rejected');
  const hasTakes = contentTakes.length > 0;
  
  // GREEN: all_approved flag is set (reached required approval count)
  if (content.all_approved) {
    return { status: 'green', color: 'success.main', approvedCount };
  }
  
  // GRAY: No takes generated yet
  if (!hasTakes) {
    return { status: 'gray', color: 'text.disabled', approvedCount };
  }
  
  // RED: Has takes but none approved (or only rejected)
  if (approvedCount === 0) {
    return { status: 'red', color: 'error.main', approvedCount };
  }
  
  // YELLOW: Has some approved but not complete
  return { status: 'yellow', color: 'warning.main', approvedCount };
}

function getSectionStatus(sectionItem, content, takes) {
  // If section is explicitly marked complete, it's green
  if (sectionItem.section_complete) {
    return { status: 'green', color: 'success.main' };
  }

  const sectionContent = content.filter(
    c =>
      c.actor_id === sectionItem.actor_id &&
      c.content_type === sectionItem.content_type &&
      c.section_id === sectionItem.id
  );
  
  if (sectionContent.length === 0) {
    return { status: 'gray', color: 'text.disabled' };
  }

  // Aggregate child statuses with explicit precedence:
  // RED > YELLOW > GRAY (never green unless section_complete is true)
  let hasRed = false;
  let hasYellow = false;
  let hasAnyProgress = false;

  for (const c of sectionContent) {
    const status = getContentStatus(c, takes);
    if (status.status === 'red') hasRed = true;
    else if (status.status === 'yellow') hasYellow = true;
    else if (status.status === 'green') hasYellow = true; // Treat cue completion as yellow until section marked complete
    
    if (status.status !== 'gray') hasAnyProgress = true;
  }

  if (hasRed) return { status: 'red', color: 'error.main' };
  if (hasYellow) return { status: 'yellow', color: 'warning.main' };
  if (hasAnyProgress) return { status: 'yellow', color: 'warning.main' };
  return { status: 'gray', color: 'text.disabled' };
}

function getActorStatus(actor, sections, content, takes) {
  // If actor is explicitly marked complete, it's green
  if (actor.actor_complete) {
    return { status: 'green', color: 'success.main' };
  }

  const actorSections = sections.filter(s => s.actor_id === actor.id);
  
  if (actorSections.length === 0) {
    return { status: 'gray', color: 'text.disabled' };
  }
  
  // Get worst status among children (never green unless actor_complete is true)
  let worstPriority = -1;
  let worstStatus = { status: 'gray', color: 'text.disabled' };
  
  for (const s of actorSections) {
    const status = getSectionStatus(s, content, takes);
    const priority = STATUS_PRIORITY[status.status];
    if (priority > worstPriority) {
      worstPriority = priority;
      worstStatus = status;
    }
  }
  
  // If any progress exists but actor not marked complete, force yellow
  if (worstStatus.status === 'green') {
    return { status: 'yellow', color: 'warning.main' };
  }
  
  return worstStatus;
}

export default function TreePane({ width, actors, content, sections, takes = [], selectedNode, onSelect, onExpandNode, playingTakeId, playedTakes = {} }) {
  const selectedId = selectedNode ? nodeKey(selectedNode.type, selectedNode.id) : null;
  
  // Load expanded state from localStorage or use defaults
  const loadExpandedState = () => {
    try {
      const saved = localStorage.getItem('audiomanager-tree-expanded');
      if (saved) {
        return JSON.parse(saved);
      }
    } catch (e) {
      console.warn('Failed to load tree state from localStorage:', e);
    }
    // Default: everything collapsed
    return {
      actors: false,
      defaults: false,
      ...actors.reduce((acc, actor) => ({ ...acc, [`actor-${actor.id}`]: false }), {})
    };
  };

  const [expanded, setExpanded] = useState(loadExpandedState);

  const handleSelect = (type, id) => {
    onSelect({ type, id });
  };

  const handleToggle = (key) => {
    setExpanded(prev => {
      const newState = { ...prev, [key]: !prev[key] };
      // Save to localStorage
      try {
        localStorage.setItem('audiomanager-tree-expanded', JSON.stringify(newState));
      } catch (e) {
        console.warn('Failed to save tree state to localStorage:', e);
      }
      return newState;
    });
  };

  const expandNode = useCallback((key) => {
    setExpanded(prev => {
      const newState = { ...prev, [key]: true };
      // Save to localStorage
      try {
        localStorage.setItem('audiomanager-tree-expanded', JSON.stringify(newState));
      } catch (e) {
        console.warn('Failed to save tree state to localStorage:', e);
      }
      return newState;
    });
  }, []);

  // Expose expandNode to parent component
  React.useEffect(() => {
    if (onExpandNode) {
      onExpandNode(expandNode);
    }
  }, [onExpandNode, expandNode]);

  return (
    <Box
      sx={{
        width: width || 300,
        flexShrink: 0,
        borderRight: 1,
        borderColor: 'divider',
        height: '100%',
        maxHeight: '100%',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}
    >
      <List dense disablePadding sx={{ px: '0.3125rem', py: '0.625rem', flexGrow: 1, overflowY: 'auto', overflowX: 'hidden' }}>
        {/* Render sections in order: Defaults first, then alphabetically */}
        {(() => {
          // Define all available sections with their properties
          const allSections = [
            {
              id: 'actors',
              name: 'actors',
              icon: <PersonIcon sx={{ fontSize: '0.875rem', color: 'text.secondary' }} />,
              nodeType: 'root',
              nodeId: 'project',
              order: 0, // Actors first
              children: null // Special handling for actors
            },
            {
              id: 'history',
              name: 'history',
              icon: <TerminalIcon sx={{ fontSize: '0.875rem', color: 'text.secondary' }} />,
              nodeType: 'console',
              nodeId: 'logs',
              order: 1, // After Actors
              children: null, // No children
              noExpand: true // Don't show expand/collapse
            },
            {
              id: 'defaults',
              name: 'defaults',
              icon: <SettingsIcon sx={{ fontSize: '0.875rem', color: 'text.secondary' }} />,
              nodeType: 'defaults',
              nodeId: 'providers',
              order: 2, // After History
              children: ['dialogue', 'music', 'sfx'].map((type) => ({
                id: type,
                name: `${type} (elevenlabs)`,
                icon: type === 'dialogue' ? <RecordVoiceOverIcon sx={{ fontSize: '0.75rem', color: 'text.secondary' }} /> :
                      type === 'music' ? <MusicNoteIcon sx={{ fontSize: '0.75rem', color: 'text.secondary' }} /> : <GraphicEqIcon sx={{ fontSize: '0.75rem', color: 'text.secondary' }} />,
                nodeType: 'provider-default',
                nodeId: type
              }))
            }
            // Future sections like 'Master', 'Templates', etc. can be added here
          ];

          // Sort sections: Defaults first (order: 0), then alphabetically by name
          const sortedSections = allSections.sort((a, b) => {
            if (a.order !== b.order) return a.order - b.order;
            return a.name.localeCompare(b.name);
          });

          return sortedSections.map((section) => (
            <React.Fragment key={section.id}>
              <ListItemButton
                className="status-gray"
                sx={{ 
                  py: '0.125rem', 
                  pl: '0.5rem',
                  pr: 0, 
                  minHeight: '1.125rem',
                  '& .MuiListItemText-root': { margin: 0 },
                  '& .MuiListItemIcon-root': { minWidth: 'auto' },
                  ...DESIGN_SYSTEM.treeItem
                }}
                selected={selectedId === nodeKey(section.nodeType, section.nodeId)}
                onClick={() => handleSelect(section.nodeType, section.nodeId)}
              >
                <ListItemIcon sx={{ minWidth: 'auto', mr: '0.25rem' }}>
                  {section.icon}
                </ListItemIcon>
                <ListItemText
                  primary={section.name}
                  primaryTypographyProps={{
                    fontSize: '0.9rem',
                    lineHeight: '1rem',
                  }}
                />
                {!section.noExpand && (
                  <Box onClick={(e) => { e.stopPropagation(); handleToggle(section.id); }} sx={{ display: 'flex', alignItems: 'center', p: 0, m: 0 }}>
                    {expanded[section.id] ? <ExpandLess sx={{ fontSize: '0.75rem' }} /> : <ExpandMore sx={{ fontSize: '0.75rem' }} />}
                  </Box>
                )}
              </ListItemButton>

              {!section.noExpand && (
              <Collapse in={expanded[section.id]} timeout="auto" unmountOnExit>
                <List component="div" disablePadding>
                  {section.children ? (
                    // Render predefined children (like provider defaults)
                    section.children.map((child) => (
                      <ListItemButton
                        key={child.id}
                        className="status-gray"
                        sx={{ 
                          pl: '1.5rem', 
                          py: 0, 
                          pr: 0, 
                          minHeight: '1.125rem',
                          '& .MuiListItemText-root': { margin: 0 },
                          '& .MuiListItemIcon-root': { minWidth: 'auto' },
                          ...DESIGN_SYSTEM.treeItem
                        }}
                        selected={selectedId === nodeKey(child.nodeType, child.nodeId)}
                        onClick={() => handleSelect(child.nodeType, child.nodeId)}
                      >
                        <ListItemIcon sx={{ minWidth: 'auto', mr: '0.25rem' }}>
                          {child.icon}
                        </ListItemIcon>
                        <ListItemText 
                          primary={child.name} 
                          primaryTypographyProps={{ 
                            fontSize: '0.9rem', 
                            lineHeight: '1rem',
                          }} 
                        />
                      </ListItemButton>
                    ))
                  ) : section.id === 'actors' ? (
                    // Special handling for actors section
                    actors.map((actor) => {
                      const actorKey = `actor-${actor.id}`;
                      const actorStatus = getActorStatus(actor, sections, content, takes);
                      return (
                        <Box key={actor.id}>
                          <ListItemButton
                            className={getStatusClass(actorStatus.color)}
                            sx={{ 
                              pl: '1.5rem', 
                              py: 0, 
                              pr: 0, 
                              minHeight: '1.125rem',
                              '& .MuiListItemText-root': { margin: 0 },
                              '& .MuiListItemIcon-root': { minWidth: 'auto' },
                              ...DESIGN_SYSTEM.treeItem,
                            }}
                            selected={selectedId === nodeKey('actor', actor.id)}
                            onClick={() => handleSelect('actor', actor.id)}
                          >
                            <ListItemIcon sx={{ minWidth: 'auto', mr: '0.25rem' }}>
                              <PersonIcon sx={{ fontSize: '0.75rem' }} />
                            </ListItemIcon>
                            <ListItemText
                              primary={actor.display_name}
                              primaryTypographyProps={{
                                fontSize: '0.9rem',
                                lineHeight: '1rem',
                                fontWeight: 400,
                              }}
                            />
                            <Box onClick={(e) => { e.stopPropagation(); handleToggle(actorKey); }} sx={{ display: 'flex', alignItems: 'center', p: 0, m: 0 }}>
                              {expanded[actorKey] ? <ExpandLess sx={{ fontSize: '0.75rem' }} /> : <ExpandMore sx={{ fontSize: '0.75rem' }} />}
                            </Box>
                          </ListItemButton>

                          <Collapse in={expanded[actorKey]} timeout="auto" unmountOnExit>
                            <List component="div" disablePadding>
                              {sections.filter(s => s.actor_id === actor.id).map((sectionItem) => {
                                const sectionType = sectionItem.content_type;
                                const sectionStatus = getSectionStatus(sectionItem, content, takes);

                                const sectionIcon = sectionType === 'dialogue' ? <RecordVoiceOverIcon sx={{ fontSize: '0.75rem' }} /> :
                                                  sectionType === 'music' ? <MusicNoteIcon sx={{ fontSize: '0.75rem' }} /> : <GraphicEqIcon sx={{ fontSize: '0.75rem' }} />;
                                const sectionKey = `section-${sectionItem.id}`;
                                
                                // Use the section item for custom name
                                const displayName = sectionItem?.name || sectionType;

                                return (
                                  <Box key={sectionItem.id}>
                                    <ListItemButton
                                      className={getStatusClass(sectionStatus.color)}
                                      sx={{ 
                                        pl: '2.5rem', 
                                        py: 0, 
                                        pr: 0, 
                                        minHeight: '1.125rem',
                                        '& .MuiListItemText-root': { margin: 0 },
                                        '& .MuiListItemIcon-root': { minWidth: 'auto' },
                                        ...DESIGN_SYSTEM.treeItem,
                                      }}
                                      selected={selectedId === nodeKey(`${sectionType}-section`, sectionItem.id)}
                                      onClick={() => handleSelect(`${sectionType}-section`, sectionItem.id)}
                                    >
                                      <ListItemIcon sx={{ minWidth: 'auto', mr: '0.25rem' }}>
                                        {sectionIcon}
                                      </ListItemIcon>
                                      <ListItemText primary={displayName} primaryTypographyProps={{ fontSize: '0.9rem', lineHeight: '1rem', fontWeight: 400 }} />
                                      <Box onClick={(e) => { e.stopPropagation(); handleToggle(sectionKey); }} sx={{ display: 'flex', alignItems: 'center', p: 0, m: 0 }}>
                                        {expanded[sectionKey] ? <ExpandLess sx={{ fontSize: '0.75rem' }} /> : <ExpandMore sx={{ fontSize: '0.75rem' }} />}
                                      </Box>
                                    </ListItemButton>

                                    <Collapse in={expanded[sectionKey]} timeout="auto" unmountOnExit>
                                      <List component="div" disablePadding>
                                        {content
                                          .filter(
                                            (c) =>
                                              c.actor_id === actor.id &&
                                              c.content_type === sectionType &&
                                              c.section_id === sectionItem.id
                                          )
                                          .map((c) => {
                                            const contentStatus = getContentStatus(c, takes);
                                            const contentTakes = takes.filter(t => t.content_id === c.id);
                                            const newCount = contentTakes.filter(t => t.status === 'new' && !playedTakes[t.id]).length;

                                            let displayText = contentStatus.approvedCount > 0 
                                              ? `${c.cue_id || c.id} (${contentStatus.approvedCount})`
                                              : (c.cue_id || c.id);

                                            if (newCount > 0) {
                                              displayText += ` (${newCount} new)`;
                                            }

                                            // Check if any take of this content is currently playing
                                            const contentTakesForPlaying = takes.filter(t => t.content_id === c.id);
                                            const isPlaying = contentTakesForPlaying.some(t => t.id === playingTakeId);

                                            const contentIcon = sectionType === 'dialogue'
                                              ? <RecordVoiceOverIcon sx={{ fontSize: '0.625rem' }} />
                                              : sectionType === 'music'
                                                ? <MusicNoteIcon sx={{ fontSize: '0.625rem' }} />
                                                : <GraphicEqIcon sx={{ fontSize: '0.625rem' }} />;

                                            return (
                                              <ListItemButton
                                                key={c.id}
                                                className={isPlaying ? 'status-white' : getStatusClass(contentStatus.color)}
                                                sx={{ 
                                                  pl: '3.5rem', 
                                                  py: 0, 
                                                  pr: 0, 
                                                  minHeight: '1.125rem',
                                                  '& .MuiListItemText-root': { margin: 0 },
                                                  '& .MuiListItemIcon-root': { minWidth: 'auto' },
                                                  ...DESIGN_SYSTEM.treeItem,
                                                }}
                                                selected={selectedId === nodeKey('content', c.id)}
                                                onClick={() => handleSelect('content', c.id)}
                                              >
                                                <ListItemIcon sx={{ minWidth: 'auto', mr: '0.25rem' }}>
                                                  {contentIcon}
                                                </ListItemIcon>
                                                <ListItemText 
                                                  primary={displayText} 
                                                  primaryTypographyProps={{ 
                                                    fontSize: '0.9rem',
                                                    lineHeight: '1rem',
                                                    fontWeight: 400,
                                                  }} 
                                                />
                                              </ListItemButton>
                                            );
                                          })}
                                      </List>
                                    </Collapse>
                                  </Box>
                                );
                              })}
                            </List>
                          </Collapse>
                        </Box>
                      );
                    })
                  ) : null}
                </List>
              </Collapse>
              )}
            </React.Fragment>
          ));
        })()}
      </List>

      {/* Color Legend at bottom - 2 rows, 2 columns */}
      <Box sx={{ px: '1rem', py: '0.375rem', color: 'text.secondary', borderTop: 1, borderColor: 'divider', flexShrink: 0, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.125rem 0.5rem' }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
          <Box sx={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', bgcolor: 'success.main' }} />
          <Typography variant="caption" sx={{ fontSize: '0.6rem', lineHeight: 1.1 }}>Complete</Typography>
        </Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
          <Box sx={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', bgcolor: 'warning.main' }} />
          <Typography variant="caption" sx={{ fontSize: '0.6rem', lineHeight: 1.1 }}>In Progress</Typography>
        </Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
          <Box sx={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', bgcolor: 'error.main' }} />
          <Typography variant="caption" sx={{ fontSize: '0.6rem', lineHeight: 1.1 }}>No Approvals</Typography>
        </Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
          <Box sx={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', bgcolor: 'text.disabled' }} />
          <Typography variant="caption" sx={{ fontSize: '0.6rem', lineHeight: 1.1 }}>Not Started</Typography>
        </Box>
      </Box>
    </Box>
  );
}
